name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Checkout agbcc compiler
        uses: actions/checkout@v4
        with:
          path: 'agbcc'
          repository: 'pret/agbcc'

      - name: Install system build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpng-dev gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Build agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: ./agbcc

      - name: Build internal tools sequentially
        run: |
          make -C tools/gbagfx
          make -C tools/scaninc
          make -C tools/preproc
          make -C tools/ramscrgen
          make tools

      - name: Build ROM
        run: |
          make -j$(nproc) all

      - name: Upload Playable ROM
        uses: actions/upload-artifact@v4
        with:
          name: pokefirered_roms
          path: "*.gba"